name: dittobox_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: 0.19.0
  path: ^1.9.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.2
  skeletons: ^0.0.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
